/*
 * systemd generator for dbus.
 *
 * generates systemd service files based on dbus service files.
 *
 * compile with -DTHREADS to spawn a thread for each file.
 */

#define _GNU_SOURCE
#define _XOPEN_SOURCE 500

#include <ftw.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <stdbool.h>
#include <unistd.h>
#include <ctype.h>
#include <sys/wait.h>
#include <dirent.h>
#include <limits.h>
#ifdef THREADS
#include <pthread.h>
#endif
#include "aasprintf.h"

#define streq(s1,s2) (!strcmp(s1,s2))
#define strneq(s1,s2,n) (!strncmp(s1,s1,n))

#define DBUS_DEFAULT_SERVICE_DIR "/usr/share/dbus-1/services"

const char *systemd_service_dir;

char *str_split_one(char *str, char d)
{
	char *ret = strchr(str, d);
	if (!ret)
		return NULL;
	*ret = '\0';
	return ret+1;
}

char *trim(char *s)
{
	char * p = s;
	int l = strlen(p);

	while (isspace(p[l - 1])) p[--l] = 0;
	while (* p && isspace(* p)) ++p, --l;
	memmove(s, p, l + 1);
	return s;
}

void *convert_file(void *arg)
{
	bool header = false;
	char line[LINE_MAX];
	char *name = NULL;
	char *exec = NULL;
	char *path = NULL;
	char *outname = NULL;
	FILE *file = NULL;

	path = aasprintf(100,DBUS_DEFAULT_SERVICE_DIR "/%s", (char *)arg);
#ifdef THREADS
	free(arg);
#endif
	file = fopen(path, "r");
	if (!file)
		goto fail;;
	while (fgets(line, LINE_MAX, file)) {
		char *val = str_split_one(line, '=');
		trim(line);
		if (val)
			trim(val);
		switch (line[0]) {
		case '#':
			break;
		case '[':
			if (streq(line, "[D-BUS Service]"))
				header = true;
			else 
				header = false;
			break;
		default:
			if (!header || !val)
				break;
			if (streq(line, "Name"))
				name = strdupa(val);
			if (streq(line, "Exec"))
				exec = strdupa(val);
			break;
		}
		if (name && exec)
			break;
	}
	fclose(file);
	if (!name || !exec)
		goto fail;

	outname = aasprintf(250, "%s/dbus-%s.service", systemd_service_dir, name);
	file = fopen(outname, "w");
	if (!file)
		goto fail;
	fprintf(file, "# Generated by the systemd-DBus generator\n"
			"[Unit]\n"
			"Description=DBUS: %s\n"
			"SourcePath=%s\n\n"
			"[Service]\n"
			"Type=dbus\n"
			"BusName=%s\n"
			"ExecStart=%s\n",
			name, path, name, exec);
	fclose(file);
	return NULL;
fail:
	return (void *) 1;
}

int main(int argc, char *argv[])
{
	DIR *dir;
	struct dirent *ent;
	if (argc != 4)
		return EXIT_FAILURE;

	systemd_service_dir = argv[1];

	dir = opendir(DBUS_DEFAULT_SERVICE_DIR);
	if (!dir) {
		perror("opendir");
		return EXIT_FAILURE;
	}
	
	while (ent = readdir (dir)) {
#ifdef THREADS
		pthread_t tid;
#endif
		char *fpath = ent->d_name;
		int len = strlen(fpath);

		if (!streq(fpath+(len-8), ".service"))
			continue;
#ifdef THREADS
		fpath = strdup(fpath);
		if (!fpath)
			goto fail;
		if (pthread_create(&tid, NULL, convert_file, (void *) fpath))
			goto fail;

		pthread_detach(tid);
#else
		convert_file((void *) fpath);
#endif
	}
	closedir (dir);
	return 0;
fail:
	closedir(dir);
	return EXIT_FAILURE;
}
